apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-ddns
spec:
  secretName: external-ddns-cert
  dnsNames:
  - external-ddns
  - external-ddns.network
  - external-ddns.network.svc
  - external-ddns.network.svc.cluster.local
  issuerRef:
    name: local
    kind: ClusterIssuer