apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-ddns
spec:
  selector:
    matchLabels:
      app: external-ddns
  template:
    spec:
      volumes:
      - name: certs
        secret:
          secretName: external-ddns-cert
      containers:
      - name: external-ddns
        image: kferrone/external-ddns:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        envFrom:
        - configMapRef:
            name: external-ddns-env
        volumeMounts:
        - name: certs
          mountPath: /app/certs
        ports:
        - name: https
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health/liveliness
            port: https
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: https
            scheme: HTTPS
