apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
commonLabels:
  app: external-ddns
commonAnnotations:
  git.repo: https://github.com/kferrone/external-ddns
resources:
- deployment.yaml
- service.yaml
- mutatingWebhook.yaml
- cert.yaml
- sa.yaml
- role.yaml
- crb.yaml
configurations:
- konfig.yaml
configMapGenerator:
- name: external-ddns-env
  literals:
  - SERVER_PORT=443