kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-ddns
rules:
- verbs:
  - watch
  - list
  - get
  apiGroups:
  - ''
  - networking.k8s.io/v1
  resources:
  - services
  - ingress